### ISSUE TITLE
Missing Context and Capability Validation in External Service

### ISSUE THREAD

**Issue by volodymyrdovhan** [EduardoKrausME/moodle-local_kopere_mobile#9]
Hello,
I found an issue with missing capabilities and context validation in the external services.
Please review the documentation for more details:
[Context and Capability Checks - Moodle External Services](https://moodledev.io/docs/4.5/apis/subsystems/external/writing-a-service#context-and-capability-checks)

![image](https://github.com/user-attachments/assets/7818813e-db06-4da4-80b0-67c5c6a2d062)

**Comment by eduardokraus** [comment]
The MOD_HVP plugin, as well as all plugins in the "external" folder, are optional. If the Moodle administrator does not install this plugin or any other similar plugin, the respective APIs will not be called since there will be no active instances in the courses.

On the other hand, if the administrator installs HVP and includes an instance of it in a course, the associated APIs will automatically be called to interact with this functionality.

An additional example is Google Meet support, implemented in the application through the [mod_googlemeet.php](https://github.com/EduardoKrausME/moodle-local_kopere_mobile/blob/master/classes/external/mod_googlemeet.php) file. This support will only be available within the app if the administrator has installed the mod_googlemeet plugin and configured an instance in a course.

**Comment by volodymyrdovhan** [comment]
Hello @eduardokraus could you please also add validate_context() ?
https://moodledev.io/docs/4.4/apis/subsystems/external/security#validating-access-to-the-moodle-context
